#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

* ॐ-emacs 
  
  ॐ-emacs or ॐmacs, pronounced "/aum emacs/".

** Motivation: ESC SPC-macs
  
   For years, spacemacs has served me well. I have now realized, however, that it
   has held me from developing further and truly reach emacs enlightement.

   In the comfort of predefined layers and extensive configuration, I grew lazy.
   This in turn made me use Emacs not as the infinitely-configurable editor that
   is, but as just another commercial editor you install a few plugins and a
   theme in, then change the font and just use it.

   This revelation means that I must embark on a journey into transcendence. May
   RMS guide my lambdas.

** The plan

   Unfortunately, spacemacs comes with a lot of useful packages and
   configurations. My complain is how opaque these defaults are to modify, not
   the lack of utilities.

   My plan is to keep using spacemacs for a while but slowly start to replicate
   as much as possible in this configuration. Initially, I think I will *not* use
   Doom emacs as a base, as it would be another non-standard "distribution" and I
   know it will ultimately get in the way of the path of ॐmacs.

** The config

   You can find it [[./CONFIG.org][here]].
